name: app-test-task

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Source code verification
        uses: actions/checkout@v2

      - name: Installing Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Installing dependencies
        run: yarn install

      - name: Running tests
        run: yarn test

      - name: Building applications
        run: yarn build

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: npx vercel --prod --yes